//
// Generated file, do not edit! Created by nedtool 5.0 from leave.msg.
//

#ifndef __LEAVE_M_H
#define __LEAVE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>leave.msg:12</tt> by nedtool.
 * <pre>
 * message Leave
 * {
 * }
 * </pre>
 */
class Leave : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const Leave& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Leave&);

  public:
    Leave(const char *name=nullptr, int kind=0);
    Leave(const Leave& other);
    virtual ~Leave();
    Leave& operator=(const Leave& other);
    virtual Leave *dup() const {return new Leave(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Leave& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Leave& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LEAVE_M_H

